export const LOGIN = 'LOGIN';
export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const TOKEN_INVALID = 'TOKEN_INVALID';

export const REGISTER_START = 'REGISTER_START';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILED = 'REGISTER_FAILED';

export const FETCH_USER_START = 'FETCH_USER_START';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILED = 'FETCH_USER_FAILED';

export const UPDATE_USER_START = 'UPDATE_USER_START';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILED = 'UPDATE_USER_FAILED';

export const CREATE_CATALOG_START = 'CREATE_CATALOG_START';
export const CREATE_CATALOG_SUCCESS = 'CREATE_CATALOG_SUCCESS';
export const CREATE_CATALOG_FAILED = 'CREATE_CATALOG_FAILED';

export const FETCH_CATALOG_START = 'FETCH_CATALOG_START';
export const FETCH_CATALOG_SUCCESS = 'FETCH_CATALOG_SUCCESS';
export const FETCH_CATALOG_FAILED = 'FETCH_CATALOG_FAILED';

export const ADD_ITEM_CATALOG_START = 'ADD_ITEM_CATALOG_START';
export const ADD_ITEM_CATALOG_SUCCESS = 'ADD_ITEM_CATALOG_SUCCESS';
export const ADD_ITEM_CATALOG_FAILED = 'ADD_ITEM_CATALOG_FAILED';

export const DELETE_ITEM_CATALOG_START = 'DELETE_ITEM_CATALOG_START';
export const DELETE_ITEM_CATALOG_SUCCESS = 'DELETE_ITEM_CATALOG_SUCCESS';
export const DELETE_ITEM_CATALOG_FAILED = 'DELETE_ITEM_CATALOG_FAILED';

export const MODIFY_ITEM_CATALOG_START = 'DELETE_ITEM_CATALOG_START';
export const MODIFY_ITEM_CATALOG_SUCCESS ='MODIFY_ITEM_CATALOG_SUCCESS';
export const MODIFY_ITEM_CATALOG_FAILED = 'MODIFY_ITEM_CATALOG_FAILED';

export const LOGOUT ='LOGOUT';
