export const LOGIN = 'LOGIN';
export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGIN_FLUSH = 'LOGIN_FLUSH';
export const TOKEN_INVALID = 'TOKEN_INVALID';

export const REGISTER_START = 'REGISTER_START';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILED = 'REGISTER_FAILED';
export const REGISTER_FLUSH = 'REGISTER_FLUSH';

export const FETCH_USER_START = 'FETCH_USER_START';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILED = 'FETCH_USER_FAILED';

export const UPDATE_USER_START = 'UPDATE_USER_START';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILED = 'UPDATE_USER_FAILED';

export const CREATE_CATALOG_START = 'CREATE_CATALOG_START';
export const CREATE_CATALOG_SUCCESS = 'CREATE_CATALOG_SUCCESS';
export const CREATE_CATALOG_FAILED = 'CREATE_CATALOG_FAILED';

export const FETCH_CATALOG_START = 'FETCH_CATALOG_START';
export const FETCH_CATALOG_SUCCESS = 'FETCH_CATALOG_SUCCESS';
export const FETCH_CATALOG_FAILED = 'FETCH_CATALOG_FAILED';

export const ADD_ITEM_CATALOG_START = 'ADD_ITEM_CATALOG_START';
export const ADD_ITEM_CATALOG_SUCCESS = 'ADD_ITEM_CATALOG_SUCCESS';
export const ADD_ITEM_CATALOG_FAILED = 'ADD_ITEM_CATALOG_FAILED';

export const DELETE_ITEM_CATALOG_START = 'DELETE_ITEM_CATALOG_START';
export const DELETE_ITEM_CATALOG_SUCCESS = 'DELETE_ITEM_CATALOG_SUCCESS';
export const DELETE_ITEM_CATALOG_FAILED = 'DELETE_ITEM_CATALOG_FAILED';

export const MODIFY_ITEM_CATALOG_START = 'DELETE_ITEM_CATALOG_START';
export const MODIFY_ITEM_CATALOG_SUCCESS ='MODIFY_ITEM_CATALOG_SUCCESS';
export const MODIFY_ITEM_CATALOG_FAILED = 'MODIFY_ITEM_CATALOG_FAILED';

export const FETCH_SPPLIERS_LIST_START = 'FETCH_SPPLIERS_LIST_START';
export const FETCH_SPPLIERS_LIST_SUCCESS = 'FETCH_SPPLIERS_LIST_SUCCESS';
export const FETCH_SPPLIERS_LIST_FAILED = 'FETCH_SPPLIERS_LIST_FAILED';

export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAILED = 'FETCH_ORDERS_FAILED';


export const FETCH_SUPPLIER_CATALOG_START = 'FETCH_SUPPLIER_CATALOG_START';
export const FETCH_SUPPLIER_CATALOG_SUCCESS = 'FETCH_SUPPLIER_CATALOG_SUCCESS';
export const FETCH_SUPPLIER_CATALOG_FAILED = 'FETCH_SUPPLIER_CATALOG_FAILED';

export const ADD_ITEM_TO_BASKET_STATE = 'ADD_ITEM_TO_BASKET_STATE';
export const ADD_ITEM_TO_BASKET_FAILED = 'ADD_ITEM_TO_BASKET_FAILED';

export const CHECK_TOKEN_VALIDITY_SUCCESS = 'CHECK_TOKEN_VALIDITY_SUCCESS';
export const CHECK_TOKEN_VALIDITY_START = 'CHECK_TOKEN_VALIDITY_START';
export const CHECK_TOKEN_VALIDITY_FAILED = 'CHECK_TOKEN_VALIDITY_FAILED';

export const PLACE_ORDER_START = 'PLACE_ORDER_START';
export const PLACE_ORDER_SUCCESS = 'PLACE_ORDER_SUCCESS';
export const PLACE_ORDER_FAILED = 'PLACE_ORDER_FAILED';

export const FETCH_CHAT_START = 'FETCH_CHAT_START';
export const FETCH_CHAT_SUCCESS = 'FETCH_CHAT_SUCCESS';
export const FETCH_CHAT_FAILED = 'FETCH_CHAT_FAILED';

export const POST_MESSAGE_START = 'POST_MESSAGE_START';
export const POST_MESSAGE_SUCCESS = 'POST_MESSAGE_SUCCESS';
export const POST_MESSAGE_FAILED = 'POST_MESSAGE_FAILED';


export const LOGOUT ='LOGOUT';
